name: Build React Native APK Automatically

on:
  push:
    branches:
      - main  # Change to your working branch if not "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version of Node.js you're working with

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Build APK
        run: expo build:android --no-publish --release-channel default --type apk

      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-native-apk
          path: ./dist/*.apk
